import { StyleSheet } from 'react-native';
import { fonts, theme } from '../../constants/theme';

export const alunoStyles = StyleSheet.create({
  flexOne: { flex: 1 },
  footerStack: { gap: 12 },
  contentFlex: { flex: 1 },
  screenTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 24,
      lineHeight: 30,
      color: theme.textDark,
      marginBottom: 8,
    },
  screenSubtitle: {
      fontFamily: fonts.bodyRegular,
      fontSize: 15,
      lineHeight: 22,
      color: theme.textMuted,
      marginBottom: 24,
    },
  sectionLabel: {
      fontFamily: fonts.headlineBold,
      fontSize: 15,
      color: theme.textDark,
      marginBottom: 16,
    },
  uploadBox: {
      position: 'relative',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
      borderRadius: 20,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: theme.teal,
      backgroundColor: theme.bgSubtle,
      marginBottom: 24,
    },
  uploadTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: '#00685F',
      marginBottom: 4,
      textAlign: 'center',
    },
  uploadSubtitle: {
      fontFamily: fonts.bodyRegular,
      fontSize: 12,
      color: theme.textFaint,
      textAlign: 'center',
    },
  studentMapRoot: { flex: 1, backgroundColor: theme.bg },
  studentTopBar: {
      minHeight: 78,
      paddingHorizontal: 10,
      paddingVertical: 12,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      zIndex: 10,
    },
  topIdentity: { flex: 1, minWidth: 62 },
  mapHello: {
      fontFamily: fonts.headlineBold,
      fontSize: 12,
      color: theme.textDark,
    },
  mapSubtitle: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      color: theme.textMuted,
    },
  notificationDot: {
      position: 'absolute',
      top: 3,
      right: 3,
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: '#E0704F',
      borderWidth: 1,
      borderColor: '#fff',
    },
  mapCoins: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderRadius: 99,
      backgroundColor: '#FFF7DF',
    },
  mapCoinsText: { fontFamily: fonts.bodyBold, fontSize: 13, color: '#8A6415' },
  mapScrollContent: { paddingBottom: 112 },
  mapCanvas: {
      width: '100%',
      maxWidth: 390,
      alignSelf: 'center',
      position: 'relative',
      backgroundColor: theme.bg,
    },
  mapNodeWrap: {
      position: 'absolute',
      width: 80,
      height: 80,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 3,
    },
  mapNode: {
      width: 70,
      height: 70,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 6,
      borderColor: '#fff',
      ...theme.shadowCard,
    },
  mapNodeDone: { backgroundColor: theme.primary },
  mapNodeCurrent: { backgroundColor: theme.primaryLight },
  mapNodeLocked: { backgroundColor: '#E5E9E7' },
  mapNodeHalo: {
      position: 'absolute',
      width: 92,
      height: 92,
      borderRadius: 46,
      backgroundColor: 'rgba(47,143,118,.16)',
    },
  mapNodeLabel: {
      position: 'absolute',
      width: 130,
      backgroundColor: '#fff',
      borderRadius: 14,
      padding: 9,
      ...theme.shadowCard,
    },
  mapLabelRight: { left: 76 },
  mapLabelLeft: { right: 76 },
  mapNodeTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 12,
      color: theme.textDark,
    },
  mapNodeText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      color: theme.textMuted,
      marginTop: 2,
    },
  missionOverlay: {
      position: 'absolute',
      left: 14,
      right: 14,
      bottom: 16,
      zIndex: 30,
    },
  missionFixedCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,.97)',
      borderWidth: 1,
      borderColor: theme.border,
      ...theme.shadowCard,
    },
  missionFixedIcon: {
      width: 40,
      height: 40,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
    },
  missionFixedEyebrow: {
      fontFamily: fonts.bodyBold,
      fontSize: 9,
      letterSpacing: 1,
      color: theme.primaryLight,
    },
  missionFixedTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 14,
      color: theme.textDark,
    },
  missionFixedMeta: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      color: theme.textMuted,
      marginTop: 2,
    },
  notificationBellButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
    },
  secondaryAction: { alignItems: 'center', paddingVertical: 12 },
  secondaryActionText: {
      fontFamily: fonts.bodyBold,
      color: theme.primary,
      fontSize: 14,
    },
  studentFileCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      padding: 16,
      borderRadius: 18,
      backgroundColor: theme.bgSubtle,
    },
  studentFileTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 14,
      color: theme.textDark,
    },
  studentFileMeta: {
      fontFamily: fonts.bodyRegular,
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 3,
    },
  studentDownloadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
    },
  studentDownloadText: { fontFamily: fonts.bodyBold, color: theme.primary },
  studentFeedback: {
      padding: 16,
      borderRadius: 18,
      backgroundColor: '#FFF0DE',
      marginBottom: 20,
    },
  studentFeedbackLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      letterSpacing: 1,
      color: '#A65F1B',
    },
  studentFeedbackText: {
      fontFamily: fonts.bodyRegular,
      color: theme.textDark,
      marginTop: 7,
      lineHeight: 19,
    },
  uploadSelected: { backgroundColor: theme.bgSoft, borderColor: theme.primary },
  studentListCard: {
      padding: 16,
      borderRadius: 18,
      backgroundColor: theme.bgSubtle,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 12,
    },
  studentListTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 15,
      color: theme.textDark,
    },
  studentListMeta: {
      fontFamily: fonts.bodyRegular,
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 5,
    },
  studentNotificationEyebrow: {
      fontFamily: fonts.bodyBold,
      fontSize: 9.5,
      letterSpacing: 1,
      color: theme.primaryLight,
      marginBottom: 4,
    },
  studentProfileOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
      borderRadius: 18,
      backgroundColor: theme.bgSubtle,
    },
  studentProfileOptionText: {
      flex: 1,
      fontFamily: fonts.bodyBold,
      color: theme.textDark,
    },
  shopHelper: {
      fontFamily: fonts.bodyRegular,
      fontSize: 12,
      color: theme.textMuted,
      marginTop: -10,
      marginBottom: 14,
    },
  categoryBar: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 2,
      paddingBottom: 18,
    },
  categoryButton: {
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.bgSubtle,
      borderWidth: 1,
      borderColor: theme.border,
    },
  categoryButtonActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
  categoryButtonText: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: theme.textMuted,
    },
  categoryButtonTextActive: { color: '#fff' },
  shopGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      paddingBottom: 24,
    },
  shopItemCard: {
      width: '48%',
      minHeight: 176,
      borderRadius: 18,
      backgroundColor: theme.bgSoft,
      borderWidth: 2,
      borderColor: 'transparent',
      alignItems: 'center',
      padding: 12,
    },
  shopItemCardLocked: { backgroundColor: '#F3F4F4', borderColor: '#E1E5E3' },
  shopItemCardEquipped: {
      borderColor: theme.primary,
      backgroundColor: '#E5F2EE',
    },
  shopItemIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      marginBottom: 8,
    },
  shopItemIconLocked: { backgroundColor: '#E7EAE9' },
  shopItemTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 12.5,
      lineHeight: 17,
      color: theme.textDark,
      textAlign: 'center',
      minHeight: 34,
    },
  itemPriceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 8,
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: '#FFF7DF',
    },
  itemPriceText: { fontFamily: fonts.bodyBold, fontSize: 11, color: '#8A6415' },
  itemActionText: {
      fontFamily: fonts.bodyBold,
      fontSize: 10.5,
      color: theme.primary,
      textAlign: 'center',
      marginTop: 8,
    },
  itemStatusReady: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 8,
    },
  itemStatusReadyText: {
      fontFamily: fonts.bodyBold,
      fontSize: 10.5,
      color: theme.primary,
    },
  requirementBox: {
      width: '100%',
      marginTop: 7,
      padding: 7,
      borderRadius: 10,
      backgroundColor: 'rgba(23,63,55,.06)',
    },
  requirementLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 9,
      letterSpacing: 0.8,
      color: theme.textFaint,
      textTransform: 'uppercase',
      marginBottom: 2,
    },
  requirementText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      lineHeight: 14,
      color: theme.textMuted,
    },
  avatarCompactWrap: { alignItems: 'center' },
  explorerAvatarCompact: {
      width: 42,
      height: 42,
      borderRadius: 21,
      overflow: 'hidden',
    },
  explorerAvatarCompactGradient: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 21,
    },
  avatarName: {
      maxWidth: 116,
      marginTop: 5,
      alignSelf: 'center',
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 999,
      overflow: 'hidden',
      backgroundColor: 'rgba(255,255,255,0.94)',
      color: theme.primary,
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      lineHeight: 16,
      textAlign: 'center',
      textShadowColor: 'rgba(255,255,255,0.9)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
  avatarCap: {
      position: 'absolute',
      top: 6,
      width: 25,
      height: 8,
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      backgroundColor: '#83B77A',
    },
  trailWorld: { ...StyleSheet.absoluteFill, overflow: 'hidden' },
  trailSky: { ...StyleSheet.absoluteFill },
  mountainBack: {
      position: 'absolute',
      top: 90,
      left: -55,
      width: 260,
      height: 185,
      borderRadius: 130,
      backgroundColor: 'rgba(84,139,124,.10)',
      transform: [{ rotate: '28deg' }],
    },
  mountainFront: {
      position: 'absolute',
      top: 150,
      right: -80,
      width: 310,
      height: 220,
      borderRadius: 160,
      backgroundColor: 'rgba(47,143,118,.08)',
      transform: [{ rotate: '-25deg' }],
    },
  trailCloud: { position: 'absolute', width: 72, height: 25, opacity: 0.42 },
  trailCloudPuff: {
      position: 'absolute',
      left: 17,
      top: 8,
      width: 42,
      height: 16,
      borderRadius: 10,
      backgroundColor: '#fff',
    },
  trailCloudPuffTwo: { left: 6, top: 12, width: 30 },
  trailCloudPuffThree: { left: 39, top: 2, width: 25, height: 21 },
  firefly: {
      position: 'absolute',
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: '#FFE28A',
      shadowColor: '#FFD66B',
      shadowOpacity: 0.8,
      shadowRadius: 8,
    },
  trailBush: {
      position: 'absolute',
      width: 72,
      height: 34,
      borderRadius: 36,
      backgroundColor: 'rgba(30,107,92,.12)',
    },
  trailBushSmall: {
      position: 'absolute',
      width: 48,
      height: 24,
      borderRadius: 24,
      backgroundColor: 'rgba(30,107,92,.10)',
    },
  trailAvatarPosition: { position: 'absolute', left: 0, top: 0, zIndex: 8 },
  mapNodeRevision: { backgroundColor: theme.warning },
  mapNodeHaloRevision: { backgroundColor: 'rgba(164,95,8,.16)' },
  pendingBadge: {
      position: 'absolute',
      top: -5,
      right: -5,
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#E0704F',
      borderWidth: 3,
      borderColor: '#fff',
    },
  pendingBadgeText: { color: '#fff', fontFamily: fonts.bodyBold, fontSize: 11 },
  missionCardRevision: {
      borderColor: 'rgba(164,95,8,.35)',
      backgroundColor: '#FFF9F0',
    },
  missionIconRevision: { backgroundColor: theme.warning },
  missionEyebrowRevision: { color: theme.warning },
  missionMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 2,
    },
  missionCta: {
      fontFamily: fonts.bodyBold,
      fontSize: 10.5,
      color: theme.primary,
      marginTop: 4,
    },
  missionHeadingRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
  screenEyebrow: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      letterSpacing: 1.2,
      color: theme.primaryLight,
      marginBottom: 5,
    },
  coinRewardPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FFF7DF',
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 999,
    },
  coinRewardText: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: '#8A6415',
    },
  missionInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: -12,
      marginBottom: 20,
    },
  filePreview: {
      width: 64,
      height: 76,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: theme.border,
    },
  filePreviewLine: {
      width: 34,
      height: 3,
      borderRadius: 2,
      backgroundColor: theme.border,
      marginTop: 6,
    },
  filePreviewLineShort: { width: 24, marginTop: 4 },
  filePreviewHint: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      color: theme.primary,
      marginTop: 5,
    },
  feedbackEncouragement: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: theme.warning,
      marginTop: 9,
    },
  uploadIconCircle: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
      ...theme.shadowCard,
    },
  confirmSheet: {
      width: '100%',
      maxWidth: 390,
      borderRadius: 28,
      padding: 24,
      paddingTop: 30,
      backgroundColor: '#fff',
      ...theme.shadowSheet,
    },
  modalClose: {
      position: 'absolute',
      right: 16,
      top: 14,
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSubtle,
    },
  confirmTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 21,
      color: theme.textDark,
      textAlign: 'center',
      marginBottom: 8,
    },
  confirmText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 14,
      lineHeight: 20,
      color: theme.textMuted,
      textAlign: 'center',
      marginBottom: 18,
    },
  confirmFile: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 14,
      backgroundColor: theme.bgSubtle,
      marginBottom: 18,
    },
  confirmFileIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
    },
  confirmFileText: {
      flex: 1,
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: theme.textDark,
    },
  celebrationScreen: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 30,
    },
  coinCelebration: { width: '100%', alignItems: 'center', marginBottom: 18 },
  coinBurst: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      marginBottom: 8,
    },
  coinCelebrationValue: {
      fontFamily: fonts.headlineBold,
      fontSize: 30,
      color: '#9A6B11',
    },
  coinCelebrationTotal: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: theme.textMuted,
      marginTop: 3,
    },
  halfwayPreview: {
      width: 230,
      height: 34,
      marginTop: 20,
      justifyContent: 'center',
    },
  halfwayLine: { height: 8, borderRadius: 4, backgroundColor: '#D7E2DD' },
  halfwayStart: {
      position: 'absolute',
      left: 0,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.primary,
    },
  halfwayFinish: {
      position: 'absolute',
      right: 0,
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 3,
      borderColor: theme.primaryLight,
      backgroundColor: '#fff',
    },
  halfwayAvatar: {
      position: 'absolute',
      left: 104,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: '#fff',
    },
  halfwayAvatarText: { color: '#fff', fontSize: 14 },
  halfwayText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 12,
      color: theme.textMuted,
      textAlign: 'center',
      marginTop: 8,
    },
  celebrationTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 24,
      color: theme.textDark,
      textAlign: 'center',
      marginBottom: 9,
    },
  celebrationDescription: {
      fontFamily: fonts.bodyRegular,
      fontSize: 15,
      lineHeight: 22,
      color: theme.textMuted,
      textAlign: 'center',
      marginBottom: 26,
    },
  resentScreen: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 35,
    },
  resentIcon: {
      width: 82,
      height: 82,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
      marginBottom: 20,
    },
  noRewardNotice: {
      width: '100%',
      borderRadius: 14,
      padding: 12,
      backgroundColor: theme.bgSubtle,
      marginBottom: 24,
    },
  noRewardText: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: theme.textMuted,
      textAlign: 'center',
    },
  rewardScreen: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 25,
    },
  chestStage: {
      width: 230,
      height: 205,
      alignItems: 'center',
      justifyContent: 'flex-end',
      marginBottom: 12,
    },
  chestBody: {
      width: 145,
      height: 90,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
  chestLid: {
      position: 'absolute',
      top: 2,
      width: 150,
      height: 42,
      borderRadius: 18,
      backgroundColor: '#7D5BD0',
      borderWidth: 5,
      borderColor: '#5B3DA8',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 3,
    },
  chestBase: {
      width: 136,
      height: 66,
      borderRadius: 17,
      backgroundColor: '#6D4BB8',
      borderWidth: 5,
      borderColor: '#543397',
    },
  rewardItem: { position: 'absolute', top: 8, alignItems: 'center', zIndex: 1 },
  rewardItemGlow: {
      position: 'absolute',
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: 'rgba(255,224,138,.24)',
    },
  exclusiveMissionPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: '#EEE8FF',
      marginTop: 9,
    },
  exclusiveMissionText: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: '#6D4BB8',
    },
  rewardTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 24,
      color: theme.textDark,
      marginBottom: 8,
    },
  rewardDescription: {
      fontFamily: fonts.bodyRegular,
      fontSize: 14,
      lineHeight: 21,
      color: theme.textMuted,
      textAlign: 'center',
      marginBottom: 24,
    },
  rewardActions: { width: '100%' },
  shopBalanceLarge: {
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#FFF7DF',
      marginTop: -8,
      marginBottom: 18,
    },
  shopBalanceLargeText: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: '#8A6415',
    },
  shopTabs: {
      flexDirection: 'row',
      gap: 8,
      padding: 5,
      borderRadius: 18,
      backgroundColor: theme.bgSubtle,
      marginBottom: 18,
    },
  shopTab: {
      flex: 1,
      minHeight: 44,
      borderRadius: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
  shopTabActive: { backgroundColor: theme.primary },
  shopTabText: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: theme.primary,
    },
  shopTabTextActive: { color: '#fff' },
  shopItemExclusive: { backgroundColor: '#F3EEFF', borderColor: '#BCAAE8' },
  shopItemExclusiveIcon: { backgroundColor: '#E5DCFA' },
  exclusiveRequirement: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginTop: 7,
      paddingHorizontal: 7,
      paddingVertical: 5,
      borderRadius: 9,
      backgroundColor: '#E5DCFA',
    },
  exclusiveRequirementText: {
      fontFamily: fonts.bodyBold,
      fontSize: 9,
      color: '#6D4BB8',
    },
  inventoryEmpty: {
      alignItems: 'center',
      padding: 28,
      borderRadius: 20,
      backgroundColor: theme.bgSubtle,
    },
  inventoryEmptyIcon: {
      width: 64,
      height: 64,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
      marginBottom: 14,
    },
  inventoryEmptyEmoji: { fontSize: 27, color: theme.primary },
  inventoryEmptyTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 16,
      color: theme.textDark,
      textAlign: 'center',
    },
  inventoryEmptyText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 13,
      color: theme.textMuted,
      textAlign: 'center',
      lineHeight: 19,
      marginTop: 6,
    },
  inventoryEmptyLink: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: theme.primary,
      marginTop: 14,
    },
  purchaseSummary: {
      borderRadius: 15,
      padding: 14,
      backgroundColor: theme.bgSubtle,
      marginBottom: 18,
    },
  purchaseLabel: {
      fontFamily: fonts.bodyRegular,
      fontSize: 11,
      color: theme.textMuted,
      marginTop: 4,
    },
  purchaseValue: {
      fontFamily: fonts.bodyBold,
      fontSize: 14,
      color: theme.textDark,
    },
  historyFilters: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingBottom: 18,
    },
  historyFilter: {
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgSubtle,
    },
  historyFilterActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
  historyFilterText: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: theme.textMuted,
    },
  historyFilterTextActive: { color: '#fff' },
  historyCardRevision: {
      borderColor: 'rgba(164,95,8,.35)',
      backgroundColor: '#FFF9F0',
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
  historyStatusIcon: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
    },
  historyStatusIconRevision: { backgroundColor: theme.warningSoft },
  notificationCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      backgroundColor: theme.bgSubtle,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 12,
    },
  notificationCardRevision: {
      backgroundColor: '#FFF9F0',
      borderColor: 'rgba(164,95,8,.3)',
    },
  notificationCardReward: {
      backgroundColor: '#F4EFFF',
      borderColor: '#CBBCEB',
    },
  notificationCardIcon: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
    },
  notificationCardIconRevision: { backgroundColor: theme.warningSoft },
  notificationCardIconReward: { backgroundColor: '#E6DDFA' },
  unreadDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#E0704F',
    },
  profileStats: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  profileStat: {
      flex: 1,
      alignItems: 'center',
      padding: 12,
      borderRadius: 16,
      backgroundColor: theme.bgSubtle,
    },
  profileStatValue: {
      fontFamily: fonts.headlineBold,
      fontSize: 17,
      color: theme.textDark,
      marginTop: 5,
    },
  profileStatLabel: {
      fontFamily: fonts.bodyRegular,
      fontSize: 10,
      color: theme.textMuted,
    },
  profilePosition: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 15,
      borderRadius: 17,
      backgroundColor: theme.bgSoft,
      marginBottom: 12,
    },
  profilePositionLabel: {
      fontFamily: fonts.bodyRegular,
      fontSize: 11,
      color: theme.textMuted,
    },
  profilePositionValue: {
      fontFamily: fonts.bodyBold,
      fontSize: 14,
      color: theme.textDark,
      marginTop: 2,
    },
  emptyMissionOverlay: {
      position: 'absolute',
      left: 14,
      right: 14,
      bottom: 16,
      zIndex: 30,
    },
  trailEmptyCard: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
      padding: 14,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,.97)',
      borderWidth: 1,
      borderColor: theme.border,
      ...theme.shadowCard,
    },
  trailEmptyIcon: {
      width: 44,
      height: 44,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
    },
  trailEmptyTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 14,
      color: theme.textDark,
    },
  trailEmptyText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 11,
      lineHeight: 15,
      color: theme.textMuted,
      marginTop: 3,
    },
  trailEmptyAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginTop: 7,
    },
  trailEmptyActionText: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: theme.primary,
    },
  categoryRail: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginHorizontal: -4,
    },
  categoryViewport: {
      flex: 1,
      minWidth: 0,
    },
  categoryArrowSlot: {
      width: 36,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
    },
  categoryArrow: {
      width: 32,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,.96)',
      borderWidth: 1,
      borderColor: theme.border,
      ...theme.shadowCard,
    },
  historyEmptyState: {
      minHeight: 220,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 22,
      paddingHorizontal: 28,
      paddingVertical: 30,
      backgroundColor: theme.bgSubtle,
      borderWidth: 1,
      borderColor: theme.border,
    },
  historyEmptyIcon: {
      width: 64,
      height: 64,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgSoft,
      marginBottom: 14,
    },
  historyEmptyTitle: {
      fontFamily: fonts.headlineBold,
      fontSize: 17,
      color: theme.textDark,
      textAlign: 'center',
    },
  historyEmptyText: {
      fontFamily: fonts.bodyRegular,
      fontSize: 13,
      lineHeight: 19,
      color: theme.textMuted,
      textAlign: 'center',
      marginTop: 7,
    },
  historyEmptyAction: {
      marginTop: 16,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.bgSoft,
    },
  historyEmptyActionText: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: theme.primary,
    },
  profileOptionStack: {
      gap: 10,
    },
  interactiveSurfacePressed: {
      opacity: 0.84,
      transform: [{ scale: 0.988 }],
    },
  interactiveChevron: {
      marginLeft: 'auto',
      transform: [{ translateX: 0 }],
    },
  studentScreenRoot: { flex: 1, backgroundColor: theme.bg },
  studentBanner: {
      height: 100,
      overflow: 'hidden',
      backgroundColor: theme.primary,
    },
  studentSheet: {
      flex: 1,
      marginTop: -18,
      overflow: 'hidden',
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: theme.card,
    },
  studentScreenContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 30,
      paddingBottom: 132,
    },
  studentFooter: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 20,
      paddingTop: 12,
      backgroundColor: 'rgba(255,255,255,0.97)',
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
  studentBackButton: {
      position: 'absolute',
      left: 14,
      zIndex: 40,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.96)',
      ...theme.shadowCard,
    },
  studentBackText: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: theme.primary,
    },
  nativeModalRoot: { flex: 1, justifyContent: 'flex-end' },
  nativeModalBackdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: theme.overlay,
    },
  nativeModalSheet: {
      maxHeight: '82%',
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 10,
      backgroundColor: theme.card,
      ...theme.shadowSheet,
    },
  nativeModalGrabber: {
      width: 42,
      height: 4,
      alignSelf: 'center',
      borderRadius: 2,
      marginBottom: 2,
      backgroundColor: theme.border,
    },
});