import { StyleSheet } from "react-native";
import { fonts, theme } from "../../constants/theme";

export const celebrationStudentStyles = StyleSheet.create({
  celebrationScreen: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 30,
  },
  coinCelebration: { width: "100%", alignItems: "center", marginBottom: 18 },
  coinBurst: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 8,
  },
  coinCelebrationValue: {
    fontFamily: fonts.headlineBold,
    fontSize: 30,
    color: theme.studentGoldDark,
  },
  coinCelebrationTotal: {
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    color: theme.textMuted,
    marginTop: 3,
  },
  halfwayPreview: {
    width: 230,
    height: 34,
    marginTop: 20,
    justifyContent: "center",
  },
  halfwayLine: {
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.studentMapTrail,
  },
  halfwayStart: {
    position: "absolute",
    left: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.primary,
  },
  halfwayFinish: {
    position: "absolute",
    right: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: theme.primaryLight,
    backgroundColor: theme.card,
  },
  halfwayAvatar: {
    position: "absolute",
    left: 104,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: theme.card,
  },
  halfwayAvatarText: { color: theme.card, fontSize: 14 },
  halfwayText: {
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    color: theme.textMuted,
    textAlign: "center",
    marginTop: 8,
  },
  celebrationTitle: {
    fontFamily: fonts.headlineBold,
    fontSize: 24,
    color: theme.textDark,
    textAlign: "center",
    marginBottom: 9,
  },
  celebrationDescription: {
    fontFamily: fonts.bodyRegular,
    fontSize: 15,
    lineHeight: 22,
    color: theme.textMuted,
    textAlign: "center",
    marginBottom: 26,
  },
  resentScreen: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 35,
  },
  resentIcon: {
    width: 85,
    height: 85,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.bgSoft,
    marginBottom: 20,
  },
  noRewardNotice: {
    width: "100%",
    borderRadius: 14,
    padding: 12,
    backgroundColor: theme.bgSubtle,
    marginBottom: 24,
  },
  noRewardText: {
    fontFamily: fonts.bodyBold,
    fontSize: 12,
    color: theme.textMuted,
    textAlign: "center",
  },
  rewardScreen: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 24,
  },
  rewardContentCard: {
    width: "100%",
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 18,
  },
  chestStage: {
    width: 220,
    height: 230,
    alignItems: "center",
    justifyContent: "flex-end",
    marginBottom: 12,
  },
  chestBody: {
    width: 145,
    height: 90,
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 18,
    zIndex: 5,
  },
  chestLid: {
    position: "absolute",
    top: 2,
    width: 149,
    height: 42,
    borderRadius: 18,
    backgroundColor: theme.studentPurple,
    borderWidth: 5,
    borderColor: theme.studentPurpleDeep,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  chestBase: {
    width: 136,
    height: 66,
    borderRadius: 17,
    backgroundColor: theme.studentPurpleDeep,
    borderWidth: 5,
    borderColor: theme.studentPurple,
  },
  rewardItem: {
    position: "absolute",
    top: 8,
    width: 150,
    height: 132,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  rewardItemContent: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  rewardItemGlow: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: theme.studentMapGlow,
    zIndex: 0,
  },
  exclusiveMissionPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: theme.studentPurpleTint,
    marginTop: 12,
    maxWidth: 150,
  },
  exclusiveMissionText: {
    fontFamily: fonts.bodyBold,
    fontSize: 10,
    color: theme.studentPurpleDeep,
  },
  rewardHeading: {
    fontFamily: fonts.headlineBold,
    fontSize: 22,
    letterSpacing: 0.8,
    color: theme.primary,
    marginBottom: 8,
    textAlign: "center",
  },
  rewardItemTitle: {
    fontFamily: fonts.headlineBold,
    fontSize: 25,
    color: theme.textDark,
    marginBottom: 18,
    textAlign: "center",
  },
  rewardDescription: {
    fontFamily: fonts.bodyRegular,
    fontSize: 14,
    lineHeight: 21,
    color: theme.textMuted,
    textAlign: "center",
    marginBottom: 22,
  },
  rewardActions: {
    width: "100%",
    marginTop: 8,
    gap: 12,
  },
});
