import { StyleSheet } from 'react-native';
import { fonts, theme } from '../../constants/theme';

export const commonStudentStyles = StyleSheet.create({
    flexOne: { flex: 1 },
    footerStack: { gap: 12 },
    contentFlex: { flex: 1 },
    screenTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 24,
        lineHeight: 30,
        color: theme.textDark,
        marginBottom: 8,
    },
    screenSubtitle: {
        fontFamily: fonts.bodyRegular,
        fontSize: 15,
        lineHeight: 22,
        color: theme.textMuted,
        marginBottom: 24,
    },
    sectionLabel: {
        fontFamily: fonts.headlineBold,
        fontSize: 15,
        color: theme.textDark,
        marginBottom: 16,
    },
    screenEyebrow: {
        fontFamily: fonts.bodyBold,
        fontSize: 10,
        letterSpacing: 1.2,
        color: theme.primaryLight,
        marginBottom: 5,
    },
    secondaryAction: { alignItems: 'center', paddingVertical: 12 },
    secondaryActionText: {
        fontFamily: fonts.bodyBold,
        color: theme.primary,
        fontSize: 14,
    },
    missionHeadingRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    missionInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
        marginTop: -12,
        marginBottom: 20,
    },
    coinRewardPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: theme.warningSoft,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 999,
    },
    coinRewardText: {
        fontFamily: fonts.bodyBold,
        fontSize: 12,
        color: theme.warning,
    },
    studentListCard: {
        padding: 16,
        borderRadius: 18,
        backgroundColor: theme.bgSubtle,
        borderWidth: 1,
        borderColor: theme.border,
        marginBottom: 12,
    },
    studentListTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 15,
        color: theme.textDark,
    },
    studentListMeta: {
        fontFamily: fonts.bodyRegular,
        fontSize: 12,
        color: theme.textMuted,
        marginTop: 5,
    },
    studentNotificationEyebrow: {
        fontFamily: fonts.bodyBold,
        fontSize: 9.5,
        letterSpacing: 1,
        color: theme.primaryLight,
        marginBottom: 4,
    },
    studentProfileOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 16,
        borderRadius: 18,
        backgroundColor: theme.bgSubtle,
    },
    studentProfileOptionText: {
        flex: 1,
        fontFamily: fonts.bodyBold,
        color: theme.textDark,
    },
    profileStats: { flexDirection: 'row', gap: 10, marginBottom: 18 },
    profileStat: {
        flex: 1,
        alignItems: 'center',
        padding: 12,
        borderRadius: 16,
        backgroundColor: theme.bgSubtle,
    },
    profileStatValue: {
        fontFamily: fonts.headlineBold,
        fontSize: 17,
        color: theme.textDark,
        marginTop: 5,
    },
    profileStatLabel: {
        fontFamily: fonts.bodyRegular,
        fontSize: 10,
        color: theme.textMuted,
    },
    profilePosition: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 15,
        borderRadius: 17,
        backgroundColor: theme.bgSoft,
        marginBottom: 12,
    },
    profilePositionLabel: {
        fontFamily: fonts.bodyRegular,
        fontSize: 11,
        color: theme.textMuted,
    },
    profilePositionValue: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.textDark,
        marginTop: 2,
    },
    interactiveSurfacePressed: {
        opacity: 0.84,
        transform: [{ scale: 0.988 }],
    },
    interactiveChevron: {
        marginLeft: 'auto',
        transform: [{ translateX: 0 }],
    },
    studentScreenRoot: { flex: 1, backgroundColor: theme.bg },
    studentBanner: {
        height: 100,
        overflow: 'hidden',
        backgroundColor: theme.primary,
    },
    studentSheet: {
        flex: 1,
        marginTop: -18,
        overflow: 'hidden',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        backgroundColor: theme.card,
    },
    studentScreenContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 132,
    },
    studentFooter: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 20,
        paddingTop: 12,
        backgroundColor: 'rgba(255,255,255,0.97)',
        borderTopWidth: 1,
        borderTopColor: theme.border,
    },
    studentBackButton: {
        position: 'absolute',
        left: 14,
        zIndex: 40,
        minHeight: 44,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 12,
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.96)',
        ...theme.shadowCard,
    },
    studentBackText: {
        fontFamily: fonts.bodyBold,
        fontSize: 13,
        color: theme.primary,
    },
    nativeModalRoot: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.28)',
    },
    nativeModalBackdrop: { flex: 1 },
    nativeModalSheet: {
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingTop: 10,
        ...theme.shadowSheet,
    },
    nativeModalGrabber: {
        width: 44,
        height: 5,
        borderRadius: 99,
        backgroundColor: '#D9DED9',
        alignSelf: 'center',
        marginBottom: 12,
    },
});