import { StyleSheet } from "react-native";
import { fonts, theme } from "../../constants/theme";

export const missionStudentStyles = StyleSheet.create({
  uploadBox: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: theme.teal,
    backgroundColor: theme.bgSubtle,
    marginBottom: 24,
  },
  uploadTitle: {
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    color: theme.tealDeep,
    marginBottom: 4,
    textAlign: "center",
  },
  uploadSubtitle: {
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    color: theme.textFaint,
    textAlign: "center",
  },
  uploadSelected: { backgroundColor: theme.bgSoft, borderColor: theme.primary },
  uploadIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: theme.card,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    ...theme.shadowCard,
  },
  studentFileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.bgSubtle,
  },
  studentFileTitle: {
    fontFamily: fonts.bodyBold,
    fontSize: 14,
    color: theme.textDark,
  },
  studentFileMeta: {
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    color: theme.textMuted,
    marginTop: 3,
  },
  studentDownloadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
  },
  studentDownloadText: { fontFamily: fonts.bodyBold, color: theme.primary },
  studentFeedback: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.studentWarmSoft,
    marginBottom: 20,
  },
  studentFeedbackLabel: {
    fontFamily: fonts.bodyBold,
    fontSize: 10,
    letterSpacing: 1,
    color: theme.studentWarm,
  },
  studentFeedbackText: {
    fontFamily: fonts.bodyRegular,
    color: theme.textDark,
    marginTop: 7,
    lineHeight: 19,
  },
  feedbackEncouragement: {
    fontFamily: fonts.bodyBold,
    fontSize: 12,
    color: theme.warning,
    marginTop: 9,
  },
  filePreview: {
    width: 64,
    height: 76,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
  },
  filePreviewLine: {
    width: 34,
    height: 3,
    borderRadius: 2,
    backgroundColor: theme.border,
    marginTop: 6,
  },
  filePreviewLineShort: { width: 24, marginTop: 4 },
  filePreviewHint: {
    fontFamily: fonts.bodyRegular,
    fontSize: 10,
    color: theme.primary,
    marginTop: 5,
  },
  confirmSheet: {
    width: "100%",
    maxWidth: 390,
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    backgroundColor: "transparent",
  },
  modalClose: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.bgSubtle,
  },
  confirmTitle: {
    fontFamily: fonts.headlineBold,
    fontSize: 21,
    color: theme.textDark,
    textAlign: "center",
    paddingHorizontal: 28,
    marginBottom: 8,
  },
  confirmText: {
    fontFamily: fonts.bodyRegular,
    fontSize: 14,
    lineHeight: 20,
    color: theme.textMuted,
    textAlign: "center",
    marginBottom: 18,
  },
  confirmFile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: theme.bgSubtle,
    marginBottom: 18,
  },
  confirmFileIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.bgSoft,
  },
  confirmFileText: {
    flex: 1,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    color: theme.textDark,
  },
});
