import { StyleSheet } from 'react-native';
import { fonts, theme } from '../../constants/theme';

export const shopStudentStyles = StyleSheet.create({
    shopHelper: {
        fontFamily: fonts.bodyRegular,
        fontSize: 12,
        color: theme.textMuted,
        marginTop: -10,
        marginBottom: 14,
    },
    categoryBar: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: 2,
        paddingBottom: 18,
    },
    categoryButton: {
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 999,
        backgroundColor: theme.bgSubtle,
        borderWidth: 1,
        borderColor: theme.border,
    },
    categoryButtonActive: {
        backgroundColor: theme.primary,
        borderColor: theme.primary,
    },
    categoryButtonText: {
        fontFamily: fonts.bodyBold,
        fontSize: 12,
        color: theme.textMuted,
    },
    categoryButtonTextActive: { color: theme.card },
    shopGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        paddingBottom: 24,
    },
    shopItemCard: {
        width: '48%',
        minHeight: 176,
        borderRadius: 18,
        backgroundColor: theme.bgSoft,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        padding: 12,
    },
    shopItemCardLocked: { backgroundColor: '#F3F4F4', borderColor: '#E1E5E3' },
    shopItemCardEquipped: {
        borderColor: theme.primary,
        backgroundColor: '#E5F2EE',
    },
    shopItemIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.card,
        marginBottom: 8,
    },
    shopItemIconLocked: { backgroundColor: '#E7EAE9' },
    shopItemTitle: {
        fontFamily: fonts.bodyBold,
        fontSize: 12.5,
        lineHeight: 17,
        color: theme.textDark,
        textAlign: 'center',
        minHeight: 34,
    },
    itemPriceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 8,
        paddingHorizontal: 9,
        paddingVertical: 5,
        borderRadius: 999,
        backgroundColor: theme.studentGoldSoft,
    },
    itemPriceText: { fontFamily: fonts.bodyBold, fontSize: 11, color: theme.studentGoldText },
    itemActionText: {
        fontFamily: fonts.bodyBold,
        fontSize: 10.5,
        color: theme.primary,
        textAlign: 'center',
        marginTop: 8,
    },
    itemStatusReady: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 8,
    },
    itemStatusReadyText: {
        fontFamily: fonts.bodyBold,
        fontSize: 10.5,
        color: theme.primary,
    },
    requirementBox: {
        width: '100%',
        marginTop: 7,
        padding: 7,
        borderRadius: 10,
        backgroundColor: 'rgba(23,63,55,.06)',
    },
    requirementLabel: {
        fontFamily: fonts.bodyBold,
        fontSize: 9,
        letterSpacing: 0.8,
        color: theme.textFaint,
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    requirementText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 10,
        lineHeight: 14,
        color: theme.textMuted,
    },
    shopBalanceLarge: {
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 13,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: theme.studentGoldSoft,
        marginTop: -8,
        marginBottom: 18,
    },
    shopBalanceLargeText: {
        fontFamily: fonts.bodyBold,
        fontSize: 13,
        color: theme.studentGoldText,
    },
    shopTabs: {
        flexDirection: 'row',
        gap: 8,
        padding: 5,
        borderRadius: 18,
        backgroundColor: theme.bgSubtle,
        marginBottom: 18,
    },
    shopTab: {
        flex: 1,
        minHeight: 44,
        borderRadius: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    shopTabActive: { backgroundColor: theme.primary },
    shopTabText: {
        fontFamily: fonts.bodyBold,
        fontSize: 12,
        color: theme.primary,
    },
    shopTabTextActive: { color: theme.card },
    shopItemExclusive: { backgroundColor: '#F3EEFF', borderColor: '#BCAAE8' },
    shopItemExclusiveIcon: { backgroundColor: theme.studentPurpleSoft },
    exclusiveRequirement: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 7,
        paddingHorizontal: 7,
        paddingVertical: 5,
        borderRadius: 9,
        backgroundColor: theme.studentPurpleSoft,
    },
    exclusiveRequirementText: {
        fontFamily: fonts.bodyBold,
        fontSize: 9,
        color: theme.studentPurpleDeep,
    },
    inventoryEmpty: {
        alignItems: 'center',
        padding: 28,
        borderRadius: 20,
        backgroundColor: theme.bgSubtle,
    },
    inventoryEmptyIcon: {
        width: 64,
        height: 64,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.bgSoft,
        marginBottom: 14,
    },
    inventoryEmptyEmoji: { fontSize: 27, color: theme.primary },
    inventoryEmptyTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 16,
        color: theme.textDark,
        textAlign: 'center',
    },
    inventoryEmptyText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 13,
        color: theme.textMuted,
        textAlign: 'center',
        lineHeight: 19,
        marginTop: 6,
    },
    inventoryEmptyLink: {
        fontFamily: fonts.bodyBold,
        fontSize: 13,
        color: theme.primary,
        marginTop: 14,
    },
    purchaseSummary: {
        borderRadius: 15,
        padding: 14,
        backgroundColor: theme.bgSubtle,
        marginBottom: 18,
    },
    purchaseLabel: {
        fontFamily: fonts.bodyRegular,
        fontSize: 11,
        color: theme.textMuted,
        marginTop: 4,
    },
    purchaseValue: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.textDark,
    },
    categoryRail: {
        minHeight: 54,
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginHorizontal: -4,
    },
    categoryViewport: {
        flex: 1,
        minWidth: 0,
    },
    categoryArrowSlot: {
        width: 36,
        height: 42,
        alignItems: 'center',
        justifyContent: 'center',
    },
    categoryArrow: {
        width: 32,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,.96)',
        borderWidth: 1,
        borderColor: theme.border,
        ...theme.shadowCard,
    },
});