import { StyleSheet, type ViewStyle } from 'react-native';
import { fonts, theme } from '../../constants/theme';

export const trailStudentStyles = StyleSheet.create({
    studentMapRoot: { flex: 1, backgroundColor: theme.bg },
    studentTopBar: {
        minHeight: 78,
        paddingHorizontal: 10,
        paddingVertical: 12,
        backgroundColor: theme.card,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
        zIndex: 10,
    },
    topIdentity: { flex: 1, minWidth: 62 },
    mapHello: {
        fontFamily: fonts.headlineBold,
        fontSize: 12,
        color: theme.textDark,
    },
    mapSubtitle: {
        fontFamily: fonts.bodyRegular,
        fontSize: 10,
        color: theme.textMuted,
    },
    notificationDot: {
        position: 'absolute',
        top: 3,
        right: 3,
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.warning,
        borderWidth: 1,
        borderColor: theme.card,
    },
    mapCoins: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 8,
        borderRadius: 99,
        backgroundColor: theme.studentGoldSoft,
    },
    mapCoinsText: { fontFamily: fonts.bodyBold, fontSize: 13, color: theme.studentGoldText },
    mapScrollContent: { paddingBottom: 112 },
    mapCanvas: {
        width: '100%',
        maxWidth: 390,
        alignSelf: 'center',
        position: 'relative',
        backgroundColor: theme.bg,
    },
    mapNodeWrap: {
        position: 'absolute',
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 3,
    },
    mapNode: {
        width: 70,
        height: 70,
        borderRadius: 35,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 6,
        borderColor: theme.card,
        ...theme.shadowCard,
    },
    mapNodeDone: { backgroundColor: theme.primary },
    mapNodeCurrent: { backgroundColor: theme.primaryLight },
    mapNodeLocked: { backgroundColor: theme.studentMapMuted },
    mapNodeHalo: {
        position: 'absolute',
        width: 92,
        height: 92,
        borderRadius: 46,
        backgroundColor: theme.studentMapPathHalo,
    },
    mapNodeLabel: {
        position: 'absolute',
        width: 130,
        backgroundColor: theme.card,
        borderRadius: 14,
        padding: 9,
        ...theme.shadowCard,
    },
    mapLabelRight: { left: 76 },
    mapLabelLeft: { right: 76 },
    mapNodeTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 12,
        color: theme.textDark,
    },
    mapNodeText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 10,
        color: theme.textMuted,
        marginTop: 2,
    },
    missionOverlay: {
        position: 'absolute',
        left: 14,
        right: 14,
        bottom: 16,
        zIndex: 30,
    },
    missionFixedCard: {
        minHeight: 72,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        padding: 12,
        borderRadius: 20,
        backgroundColor: theme.whiteGlass,
        borderWidth: 1,
        borderColor: theme.border,
        ...theme.shadowCard,
    },
    missionFixedIcon: {
        width: 40,
        height: 40,
        borderRadius: 13,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.primary,
    },
    missionFixedEyebrow: {
        fontFamily: fonts.bodyBold,
        fontSize: 9,
        letterSpacing: 1,
        color: theme.primaryLight,
    },
    missionFixedTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 14,
        color: theme.textDark,
    },
    missionFixedMeta: {
        fontFamily: fonts.bodyRegular,
        fontSize: 10,
        color: theme.textMuted,
        marginTop: 2,
    },
    missionMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 2,
    },
    missionCardRevision: {
        borderColor: theme.studentWarmBorder,
        backgroundColor: theme.studentWarmGlow,
    },
    missionIconRevision: { backgroundColor: theme.warning },
    missionEyebrowRevision: { color: theme.warning },
    missionCta: {
        fontFamily: fonts.bodyBold,
        fontSize: 10.5,
        color: theme.primary,
        marginTop: 4,
    },
    notificationBellButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.bgSoft,
    },
    mapNodeRevision: { backgroundColor: theme.warning },
    mapNodeHaloRevision: { backgroundColor: theme.studentMapPathWarning },
    pendingBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        width: 22,
        height: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.warning,
        borderWidth: 3,
        borderColor: theme.card,
    },
    pendingBadgeText: { color: theme.card, fontFamily: fonts.bodyBold, fontSize: 11 },
    emptyMissionOverlay: {
        position: 'absolute',
        left: 14,
        right: 14,
        bottom: 16,
        zIndex: 30,
    },
    trailEmptyCard: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
        padding: 14,
        borderRadius: 20,
        backgroundColor: theme.whiteSoft,
        borderWidth: 1,
        borderColor: theme.border,
        ...theme.shadowCard,
    },
    trailEmptyIcon: {
        width: 44,
        height: 44,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.bgSoft,
    },
    trailEmptyTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 14,
        color: theme.textDark,
    },
    trailEmptyText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 11,
        lineHeight: 15,
        color: theme.textMuted,
        marginTop: 3,
    },
    trailEmptyAction: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 7,
    },
    trailEmptyActionText: {
        fontFamily: fonts.bodyBold,
        fontSize: 11,
        color: theme.primary,
    },
    trailWorld: { ...StyleSheet.absoluteFill, overflow: 'hidden' },
    trailSky: { ...StyleSheet.absoluteFill },
    mountainBack: {
        position: 'absolute',
        top: 90,
        left: -55,
        width: 260,
        height: 185,
        borderRadius: 130,
        backgroundColor: theme.studentMapMist,
        transform: [{ rotate: '28deg' }],
    },
    mountainFront: {
        position: 'absolute',
        top: 150,
        right: -80,
        width: 310,
        height: 220,
        borderRadius: 160,
        backgroundColor: theme.studentMapMistDeep,
        transform: [{ rotate: '-25deg' }],
    },
    trailCloud: { position: 'absolute', width: 72, height: 25, opacity: 0.42 },
    trailCloudPuff: {
        position: 'absolute',
        left: 17,
        top: 8,
        width: 42,
        height: 16,
        borderRadius: 10,
        backgroundColor: theme.card,
    },
    trailCloudPuffTwo: { left: 6, top: 12, width: 30 },
    trailCloudPuffThree: { left: 39, top: 2, width: 25, height: 21 },
    firefly: {
        position: 'absolute',
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: theme.studentGoldAccent,
        shadowColor: theme.studentGoldGlow,
        shadowOpacity: 0.8,
        shadowRadius: 8,
    },
    trailBush: {
        position: 'absolute',
        width: 72,
        height: 34,
        borderRadius: 36,
        backgroundColor: theme.studentMapBush,
    },
    trailBushSmall: {
        position: 'absolute',
        width: 48,
        height: 24,
        borderRadius: 24,
        backgroundColor: theme.studentMapBushSoft,
    },
    trailAvatarPosition: { position: 'absolute', left: 0, top: 0, zIndex: 8 },
});

export const trailStyleHelpers = {
    trailCloudPosition: (top: number, left: number): ViewStyle => ({
        position: 'absolute' as const,
        top,
        left,
        width: 72,
        height: 25,
        opacity: 0.42,
    }),
    trailBushPosition: (top: number, left?: number, right?: number): ViewStyle => ({
        position: 'absolute' as const,
        top,
        left,
        right,
        width: 72,
        height: 34,
        borderRadius: 36,
        backgroundColor: theme.studentMapBush,
    }),
    trailBushSmallPosition: (top: number, left?: number, right?: number): ViewStyle => ({
        position: 'absolute' as const,
        top,
        left,
        right,
        width: 48,
        height: 24,
        borderRadius: 24,
        backgroundColor: theme.studentMapBushSoft,
    }),
    fireflyPosition: (top: number, left: number): ViewStyle => ({
        position: 'absolute' as const,
        top,
        left,
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: theme.studentGoldAccent,
        shadowColor: theme.studentGoldGlow,
        shadowOpacity: 0.8,
        shadowRadius: 8,
    }),
    mapNodePosition: (left: number, top: number): ViewStyle => ({
        position: 'absolute' as const,
        left,
        top,
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 3,
    }),
    mapCanvasHeight: (height: number): ViewStyle => ({
        width: '100%',
        maxWidth: 390,
        height,
        alignSelf: 'center',
        position: 'relative' as const,
        backgroundColor: theme.bg,
    }),
} as const;