import { borderRadius, fonts, theme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const educatorHeaderStyles = StyleSheet.create({
    shell: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        height: '100%',
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
        backgroundColor: theme.card,
        shadowColor: theme.textDark,
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.08,
        shadowRadius: 14,
        elevation: 6,
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        overflow: 'hidden',
    },
    overlayInner: {
        width: '100%',
        maxWidth: 1280,
        height: '100%',
        alignSelf: 'center',
        position: 'relative',
    },
    mainRow: {
        width: '100%',
        maxWidth: 1280,
        alignSelf: 'center',
        position: 'relative',
        zIndex: 2,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
    },
    identityRow: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatar: {
        flexShrink: 0,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0,
        borderColor: theme.primaryTint,
        borderRadius: 17,
        backgroundColor: theme.primary,
    },
    avatarText: {
        color: theme.white,
        fontFamily: fonts.headlineBold,
        fontSize: 15,
    },
    greetingText: {
        color: theme.textDark,
        fontFamily: fonts.headlineBold,
        fontSize: 17,
    },
    subtitleText: {
        marginTop: 2,
        color: theme.textMuted,
        fontFamily: fonts.bodyRegular,
        fontSize: 12,
    },
    navRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    navItem: {
        minHeight: 42,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
        borderRadius: borderRadius.pill,
        backgroundColor: 'transparent',
    },
    navItemActive: {
        backgroundColor: theme.bgSoft,
    },
    navItemText: {
        color: theme.textMuted,
        fontFamily: fonts.bodyRegular,
        fontSize: 13,
    },
    navItemTextActive: {
        color: theme.primary,
        fontFamily: fonts.bodyBold,
    },
    mobileActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
    },
    panel: {
        position: 'absolute',
        zIndex: 110,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: borderRadius.xxl,
        backgroundColor: theme.card,
        ...theme.shadowCard,
    },
    panelContent: {
        padding: 10,
        gap: 4,
    },
    panelItem: {
        minHeight: 48,
        paddingHorizontal: 13,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 11,
        borderRadius: borderRadius.lg,
        backgroundColor: 'transparent',
    },
    panelItemActive: {
        backgroundColor: theme.bgSoft,
    },
    panelItemText: {
        flex: 1,
        color: theme.textDark,
        fontFamily: fonts.bodyRegular,
        fontSize: 14,
    },
    panelItemTextActive: {
        color: theme.primary,
        fontFamily: fonts.bodyBold,
    },
    notificationPanel: {
        width: 390,
    },
    notificationHeader: {
        paddingHorizontal: 17,
        paddingTop: 16,
        paddingBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
    },
    notificationHeaderTitle: {
        color: theme.textDark,
        fontFamily: fonts.headlineSemibold,
        fontSize: 15,
    },
    notificationHeaderSubtitle: {
        marginTop: 3,
        color: theme.textMuted,
        fontFamily: fonts.bodyRegular,
        fontSize: 11,
    },
    emptyState: {
        paddingHorizontal: 20,
        paddingVertical: 28,
        alignItems: 'center',
    },
    emptyStateTitle: {
        marginTop: 10,
        color: theme.textDark,
        fontFamily: fonts.headlineSemibold,
        fontSize: 14,
        textAlign: 'center',
    },
    emptyStateSubtitle: {
        marginTop: 5,
        color: theme.textMuted,
        fontFamily: fonts.bodyRegular,
        fontSize: 12,
        textAlign: 'center',
    },
    notificationItem: {
        paddingHorizontal: 17,
        paddingVertical: 14,
        backgroundColor: theme.card,
    },
    notificationItemUnread: {
        backgroundColor: theme.bgSoft,
    },
    notificationItemBadge: {
        width: 8,
        height: 8,
        marginTop: 5,
        flexShrink: 0,
        borderRadius: 4,
        backgroundColor: theme.warning,
    },
    notificationItemText: {
        color: theme.textDark,
        fontFamily: fonts.bodyBold,
        fontSize: 13,
    },
    notificationItemDescription: {
        marginTop: 4,
        color: theme.textMuted,
        fontFamily: fonts.bodyRegular,
        fontSize: 12,
        lineHeight: 17,
    },
    notificationItemRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 9,
    },
    notificationItemContent: {
        flex: 1,
        minWidth: 0,
    },
    footerButton: {
        minHeight: 48,
        alignItems: 'center',
        justifyContent: 'center',
        borderTopWidth: 1,
        borderTopColor: theme.border,
        backgroundColor: theme.card,
    },
    footerButtonText: {
        color: theme.primary,
        fontFamily: fonts.bodyBold,
        fontSize: 13,
    },
});