import { StyleSheet } from 'react-native';
import { BANNER_H, borderRadius, fonts, FRAME_H, spacing, theme } from '../../constants/theme';

export const authStyles = StyleSheet.create({
    shellRoot: {
        flex: 1,
        backgroundColor: theme.bg,
    },
    shellFrame: {
        flex: 1,
    },
    shellScroll: {
        flex: 1,
        minHeight: 0,
    },
    sheetBody: {
        flex: 1,
        minHeight: 0,
    },
    shellContentContainer: {
        flexGrow: 1,
        paddingBottom: 0,
    },
    formBanner: {
        height: BANNER_H,
        position: 'relative',
        overflow: 'hidden',
    },
    sheet: {
        flex: 1,
        backgroundColor: theme.card,
        borderTopLeftRadius: borderRadius.frame,
        borderTopRightRadius: borderRadius.frame,
        paddingHorizontal: spacing.xl,
        paddingTop: spacing.xl,
        paddingBottom: 0,
        overflow: 'hidden',
        ...theme.shadowSheet,
    },
    sheetContent: {
        flexGrow: 1,
    },
    sheetFooter: {
        marginTop: spacing.md,
        paddingTop: spacing.md,
        paddingBottom: 0,
        borderTopWidth: 1,
        borderTopColor: theme.border,
        backgroundColor: theme.card,
        flexShrink: 0,
    },
    footerOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.xl,
        paddingTop: spacing.lg,
        backgroundColor: theme.whiteSubtle,
    },
    simpleHeader: {
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    authTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 24,
        lineHeight: 30,
        color: theme.textDark,
        marginBottom: 6,
    },
    authSubtitle: {
        fontFamily: fonts.bodyRegular,
        fontSize: 15,
        lineHeight: 22,
        color: theme.textMuted,
    },
    explorerAvatar: {
        width: 104,
        height: 104,
        borderRadius: borderRadius.avatar,
        alignSelf: 'center',
        marginBottom: spacing.lg,
        shadowColor: theme.shadowBtn.shadowColor,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.35,
        shadowRadius: 18,
        elevation: 10,
    },
    explorerAvatarGradient: {
        flex: 1,
        borderRadius: borderRadius.avatar,
        alignItems: 'center',
        justifyContent: 'center',
    },
    successSheet: {
        minHeight: FRAME_H - BANNER_H,
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: spacing.xxl,
    },
    successBadge: {
        width: 96,
        height: 96,
        borderRadius: borderRadius.avatar,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing.xl,
        shadowColor: theme.shadowBtn.shadowColor,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.35,
        shadowRadius: 18,
        elevation: 10,
    },
    successEmoji: {
        fontSize: 38,
    },
    successDot: {
        position: 'absolute',
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: theme.bg,
        opacity: 0.65,
    },
    successDotTopRight: {
        top: 17,
        right: 19,
    },
    successDotSmall: {
        position: 'absolute',
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.bg,
        opacity: 0.45,
    },
    successDotSmallBottomLeft: {
        bottom: 19,
        left: 20,
    },
    successTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 24,
        lineHeight: 30,
        color: theme.textDark,
        textAlign: 'center',
        marginBottom: 12,
    },
    successDescription: {
        fontFamily: fonts.bodyRegular,
        fontSize: 15,
        lineHeight: 22,
        color: theme.textMuted,
        textAlign: 'center',
        marginBottom: spacing.xl,
    },
    successFooter: {
        marginTop: spacing.sm,
        alignItems: 'center',
    },
    separator: {
        height: 1,
        backgroundColor: theme.border,
        marginTop: spacing.xl,
        marginBottom: spacing.lg,
    },
    loginLinks: {
        alignItems: 'center',
        gap: 18,
    },
    linkMuted: {
        fontFamily: fonts.bodyRegular,
        fontSize: 14,
        lineHeight: 20,
        color: theme.textMuted,
        textAlign: 'center',
    },
    linkStrong: {
        fontFamily: fonts.bodyBold,
        color: theme.primary,
    },
    recoveryHelperText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 13,
        lineHeight: 19,
        color: theme.textMuted,
        textAlign: 'center',
        marginTop: 14,
        paddingHorizontal: 4,
    },
    sentNoticeBox: {
        width: '100%',
        borderRadius: borderRadius.button,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        backgroundColor: theme.bgSoft,
        borderWidth: 1,
        borderColor: theme.primaryTint,
    },
    sentNoticeTitle: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.textDark,
        textAlign: 'center',
        marginBottom: 6,
    },
    sentNoticeText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 13,
        lineHeight: 19,
        color: theme.textMuted,
        textAlign: 'center',
    },
});