import { StyleSheet } from 'react-native';
import { borderRadius, fonts, spacing, theme } from '../../constants/theme';

export const rolesStyles = StyleSheet.create({
    roleRoot: {
        flex: 1,
        backgroundColor: theme.bg,
        justifyContent: 'center',
        paddingHorizontal: spacing.xl,
    },
    roleInner: {
        zIndex: 2,
    },
    roleHeroIconWrap: {
        width: 76,
        height: 76,
        borderRadius: borderRadius.xxl,
        alignSelf: 'center',
        marginBottom: spacing.lg,
        shadowColor: theme.shadowBtn.shadowColor,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.35,
        shadowRadius: 18,
        elevation: 10,
    },
    roleHeroIcon: {
        flex: 1,
        borderRadius: borderRadius.xxl,
        alignItems: 'center',
        justifyContent: 'center',
    },
    heroDot: {
        position: 'absolute',
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: theme.bg,
        opacity: 0.65,
    },
    heroDotTopRight: {
        top: 16,
        right: 17,
    },
    heroDotSmall: {
        position: 'absolute',
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.bg,
        opacity: 0.45,
    },
    heroDotSmallBottomLeft: {
        bottom: 17,
        left: 18,
    },
    roleTitleActive: {
        color: theme.white,
    },
    roleTitleInactive: {
        color: theme.textDark,
    },
    roleDescriptionActive: {
        color: theme.textOnPrimarySoft,
    },
    roleDescriptionInactive: {
        color: theme.textMuted,
    },
    roleEyebrow: {
        fontFamily: fonts.bodyBold,
        fontSize: 12,
        letterSpacing: 1.6,
        textTransform: 'uppercase',
        color: theme.primaryLight,
        textAlign: 'center',
        marginBottom: spacing.sm,
    },
    roleHeading: {
        fontFamily: fonts.headlineBold,
        fontSize: 24,
        lineHeight: 30,
        color: theme.textDark,
        textAlign: 'center',
        marginBottom: spacing.xs,
    },
    roleSubheading: {
        fontFamily: fonts.bodyRegular,
        fontSize: 15,
        lineHeight: 22,
        color: theme.textMuted,
        textAlign: 'center',
        marginBottom: spacing.xxl,
    },
    roleCards: {
        gap: spacing.md,
    },
    roleCard: {
        position: 'relative',
        overflow: 'hidden',
        borderRadius: borderRadius.xxl,
        padding: spacing.md,
    },
    roleCardGlow: {
        position: 'absolute',
        top: -20,
        right: -20,
        width: 130,
        height: 130,
        borderRadius: 80,
    },
    roleCardActive: {
        shadowColor: theme.shadowBtn.shadowColor,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.24,
        shadowRadius: 18,
        elevation: 8,
    },
    roleSparkle: {
        position: 'absolute',
        top: spacing.md,
        right: 22,
        width: 8,
        height: 8,
        borderRadius: 4,
        opacity: 0.55,
    },
    roleCardContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.md,
    },
    roleIconBox: {
        width: 56,
        height: 56,
        borderRadius: borderRadius.button,
        alignItems: 'center',
        justifyContent: 'center',
    },
    roleTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 16,
        marginBottom: 2,
    },
    roleDescription: {
        fontFamily: fonts.bodyRegular,
        fontSize: 13,
        lineHeight: 18,
    },
    roleArrow: {
        width: 30,
        height: 30,
        borderRadius: borderRadius.pill,
        alignItems: 'center',
        justifyContent: 'center',
    },
    educatorOptions: {
        marginTop: spacing.md,
        borderRadius: borderRadius.button,
        backgroundColor: theme.card,
        overflow: 'hidden',
        ...theme.shadowCard,
    },
    optionButton: {
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.md,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    optionText: {
        fontFamily: fonts.bodyBold,
        fontSize: 15,
        color: theme.textDark,
    },
    optionArrow: {
        fontSize: 18,
        color: theme.textFaint,
    },
    optionDivider: {
        height: 1,
        marginHorizontal: spacing.lg,
        backgroundColor: theme.border,
    },
    roleBack: {
        marginTop: spacing.xl,
        alignItems: 'center',
    },
    roleBackText: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.textFaint,
    },
});