import { Platform, StyleSheet } from 'react-native';
import { borderRadius, fonts, FRAME_H, FRAME_W, spacing, theme } from '../constants/theme';

// Estilos globais para a aplicação, incluindo configurações de layout, botões, textos e outros elementos visuais.
export const globalStyles = StyleSheet.create({
    gestureRoot: { flex: 1 },
    outerWrap: { flex: 1, backgroundColor: theme.shellBg, alignItems: 'center', justifyContent: 'center' },
    phoneFrame: {
        width: FRAME_W,
        height: FRAME_H,
        borderRadius: Platform.OS === 'web' ? borderRadius.frame : 0,
        overflow: 'hidden',
        borderWidth: Platform.OS === 'web' ? 8 : 0,
        borderColor: theme.frameBorder,
        ...(Platform.OS === 'web' ? { shadowColor: theme.shadowCard.shadowColor, shadowOffset: { width: 0, height: 30 }, shadowOpacity: 0.35, shadowRadius: 60 } : {}),
    },
    bgItem: { position: 'absolute' },
    iconCardWrap: {
        width: 104,
        height: 104,
        borderRadius: borderRadius.card,
        marginBottom: spacing.xl,
        shadowColor: theme.shadowBtn.shadowColor,
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.45,
        shadowRadius: 20,
        elevation: 10,
    },
    iconCard: {
        flex: 1,
        borderRadius: borderRadius.card,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconCardHaloBorder: {
        position: 'absolute',
        top: -8,
        left: -8,
        right: -8,
        bottom: -8,
        borderRadius: borderRadius.card - 1,
        borderWidth: 1,
        borderColor: theme.whiteBorder,
    },
    iconCardSparkle: {
        position: 'absolute',
        backgroundColor: theme.bg,
    },
    primaryBtn: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: spacing.md, paddingHorizontal: spacing.lg, borderRadius: borderRadius.button },
    primaryBtnText: { color: theme.card, fontFamily: fonts.headlineSemibold, fontSize: 16 },
    dotsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    dot: {
        height: 6,
        borderRadius: 3,
    },
    ctaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    btnShine: {
        position: 'absolute',
        top: 10,
        right: 18,
        width: 10,
        height: 10,
        borderRadius: 45,
        backgroundColor: theme.whiteFaint,
    },
    eyebrow: { fontFamily: fonts.bodyBold, fontSize: 12, letterSpacing: 1.5, textTransform: 'uppercase', color: theme.primaryLight, marginBottom: spacing.sm, textAlign: 'center' },
    floatingBack: {
        position: 'absolute',
        top: spacing.md,
        left: spacing.lg,
        zIndex: 40,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: theme.whiteSoft,
        paddingHorizontal: spacing.sm,
        paddingVertical: 7,
        borderRadius: borderRadius.pill,
        shadowColor: theme.shadowCard.shadowColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 6,
    },
    floatingBackText: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.primary,
    },
    authHeader: {
        marginBottom: spacing.xl,
    },
    centerItems: {
        alignItems: 'center',
    },
    leftItems: {
        alignItems: 'flex-start',
    },
    textCenter: {
        textAlign: 'center',
    },
    textLeft: {
        textAlign: 'left',
    },
    inputLabel: {
        fontFamily: fonts.bodyBold,
        color: theme.textDark,
        marginLeft: 4,
    },
    input: {
        width: '100%',
        borderWidth: 2,
        borderColor: theme.border,
        color: theme.textDark,
        fontFamily: fonts.bodyRegular,
    },
    manualLabel: {
        fontFamily: fonts.bodyBold,
        color: theme.textDark,
        fontSize: 13,
        marginLeft: 4,
        marginBottom: spacing.sm,
    },
    helperText: {
        fontFamily: fonts.bodyRegular,
        fontSize: 12.5,
        lineHeight: 18,
        textAlign: 'center',
        color: theme.textMuted,
        marginTop: 14,
        paddingHorizontal: spacing.sm,
    },
    formStack: {
        gap: spacing.md,
    },
    fieldWrap: {
        gap: 6,
    },
    keyboardView: {
        flex: 1,
    },
    ctaSpacer: {
        height: 56,
    },
    scrollContentMinHeight: {
        minHeight: FRAME_H,
    },
    headerTitleSpacing: {
        marginTop: 15,
    },
    primaryButtonWrapper: {
        width: '100%',
        borderRadius: borderRadius.button,
    },
    contextBody: {
        flex: 1,
    },
    skipSecondaryActive: {
        opacity: 1,
    },
    skipSecondaryMuted: {
        opacity: 0.45,
    },
    errorText: {
        fontFamily: fonts.bodyBold,
        color: theme.danger,
        fontSize: 12,
        marginLeft: 4,
        marginTop: -6,
    },
    skipButton: {
        alignItems: 'center',
    },
    skipSecondary: {
        fontFamily: fonts.bodyBold,
        fontSize: 14,
        color: theme.textFaint,
    },
    screenTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 24,
        lineHeight: 30,
        color: theme.textDark,
        marginBottom: spacing.sm,
    },
    screenSubtitle: {
        fontFamily: fonts.bodyRegular,
        fontSize: 15,
        lineHeight: 22,
        color: theme.textMuted,
        marginBottom: spacing.xl,
    },
    contextCard: {
        position: 'relative',
        overflow: 'hidden',
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.md,
        padding: spacing.md,
        borderRadius: borderRadius.panel,
        backgroundColor: theme.bgSubtle,
        marginBottom: 28,
    },
    contextIcon: {
        width: 48,
        height: 48,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contextLabel: {
        fontFamily: fonts.bodyBold,
        fontSize: 11,
        letterSpacing: 1.1,
        textTransform: 'uppercase',
        color: theme.textMuted,
        marginBottom: 2,
    },
    contextTitle: {
        fontFamily: fonts.headlineBold,
        fontSize: 15,
        color: theme.textDark,
    },
    sectionLabel: {
        fontFamily: fonts.headlineBold,
        fontSize: 15,
        color: theme.textDark,
        marginBottom: spacing.md,
    },
});